### ISSUE TITLE
feature request: choose default to hints off

### ISSUE THREAD

**Issue by haughki** [mdbridge/click-by-voice#3]
click-by-voice is amazing. Many, many thanks, up front, for your work.

feature: I'd like to have a configuration setting so that I could configure click-by-voice with a default setting: open all pages either in "show hints mode" or "hide hints mode".

extra if possible: a command to toggle the setting.

use case: Right now, click-by-voice defaults to always show hints: every time a new page opens, all of the hints render. Sometimes this is what I want. But other times, I would like to have hints off to start, and then show them if I need to. E.g., I'm working with some pages where the hints throw the formatting way off. Or, there are MANY hints and it just takes a long time to render. Or I'm in a mode where I need to _read_ the page more than I need to _browse_ the page.

Thanks again for click-by-voice!

**Comment by mdbridge** [comment]
Hawkeye Parker <notifications@github.com> writes:

> click-by-voice is amazing. Many, many thanks, up front, for your work.
> 
> feature: I'd like to have a configuration setting so that I could configure
> click-by-voice with a default setting: open all pages either in "show hints
> mode" or "hide hints mode".
> 
> extra if possible: a command to toggle the setting.
> 
> use case: Right now, click-by-voice defaults to always show hints: every
> time a new page opens, all of the hints render. Sometimes this is what I
> want. But other times, I would like to have hints off to start, and then
> show them if I need to. E.g., I'm working with some pages where the hints
> throw the formatting way off. Or, there are MANY hints and it just takes a
> long time to render. Or I'm in a mode where I need to read the page more
> than I need to browse the page.

I think I implemented all of this in the last release.  See https://github.com/mdbridge/click-by-voice:

Displaying hints
You can change how hints are displayed for the current tab by using a show hints command. The simplest such commands are:

:+ shows standard hints
:++ is similar but displays more hints, attempting to hint every element that might be clickable or focusable, however unlikely that might be
:- shows no hints
To use these commands, just enter them into the hint number popup instead of a hint number.

Click by Voice normally remembers the last such command you have given (in any tab) and automatically uses it when a new page is loaded or the current tab is reloaded. If you want to only temporarily change how hints are displayed for a tab, add once after the colon; for example, :once- turns off hints for the current tab until it is refreshed and does not affect future loads of other tabs.

The hinting system is highly flexible, with these commands taking many optional switches. For details, including how to change startup defaults, see displaying hints in detail

- Mark
